### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [howell33/project7#1]
I broke it. :cry: It looks like when I try to submit a blank form, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid a blank form being submitted.

Let me know when it's updated and I'll take another look.

**Comment by chrisvfritz** [comment]
I see you've made some progress on this. I still see some issues though. When I submit the form, I expect to see my changes saved in the form, as specified in the project (`every form field should always show the current parameters`). You can do [something like this](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) to make sure the current params are reflected in the form.

I also get an `Internal Server Error` when I enter a number greater than 12 for the month. I recommend using the `min` and `max` attributes for number inputs to prevent this.

Please post a comment here when you've made this update, so that I know to take another look.

**Comment by howell33** [comment]
updated.

I do have one question though.
In my index.erb file I tried [ value="month"] and that did not work but when I did [ value="<%= params['month'] %>" ] it worked. Why didn't the first attempt work?

**Comment by chrisvfritz** [comment]
It looks like I'm getting an `Internal Server Error` when first visiting your app now. You should able to fix this by [assigning some defaults in `app.rb` on line 6](https://github.com/howell33/project7/blob/master/app.rb#L6).

You could do so with something like:

``` ruby
get '/' do
  current_time = Time.now
  params['month'] ||= current_time.month.to_s
  params['year'] ||= current_time.year.to_s
  params['day'] ||= current_time.day.to_s
  @holidays = HolidApi.get(country: 'us', month: params['month'], year: params['year'], day: params['day']).flatten
  @old_holiday = HolidApi.get(country: 'us', month: 11, year: 1992).flatten
  erb :index
end
```

Regarding your excellent question, the reason `value="month"` didn't work, but `value="<%= params['month'] %>"` did, is the first assigns a value of the word "month" and the second assigns a value of what is _inside of_ `params['month']`, which should be a number like we want.

It's kind of like if you ask a friend, "Can you tell me your phone number?" and instead of giving your their actual phone number, they decide to be obnoxious and just say, "Your phone number. Oh, what's wrong? You asked me to tell you _your phone number_ and that's exactly what I told you."

In our case, the actual values submitted by the forms are stored in the `params` hash and we access each of them by saying what we want with `params['month']` or `params['year']`, for example. Then we put that inside of `<%= %>` to tell our `.erb` file that this isn't HTML, but rather Ruby we're injecting into our HTML.

Let me know if that makes sense. If it doesn't, I'll be happy to explain another way.

**Comment by howell33** [comment]
updated

**Comment by chrisvfritz** [comment]
:+1: Looks good!
